# Generated by Django 3.0.3 on 2020-05-15 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('btype', models.CharField(max_length=100)),
                ('hq', models.CharField(max_length=100)),
                ('estd', models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 4', regex='^.{4}$')])),
            ],
        ),
    ]
