# Generated by Django 3.0.3 on 2020-05-15 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('bank', models.CharField(max_length=100)),
                ('card', models.BigIntegerField(validators=[django.core.validators.MinLengthValidator(12)])),
                ('pvtkey', models.CharField(max_length=100, null=True)),
                ('binary', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
